name: Mac Ngrok Tunnel

on: [workflow_dispatch]

jobs:
  tunnel:
    runs-on: macos-latest

    steps:
    - name: Install Ngrok
      run: |
        curl -o ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip
        unzip ngrok.zip
        chmod +x ngrok
        mv ngrok /usr/local/bin/ngrok

    - name: Auth Ngrok
      run: ngrok config add-authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start Local Server
      run: |
        nohup python3 -m http.server 8000 &

    - name: Start Ngrok Tunnel
      run: |
        nohup ngrok http 8000 > ngrok.log &
        sleep 5
        grep -o 'https://[0-9a-z]*\.ngrok.io' ngrok.log || true

    - name: Keep Runner Alive (6 hours)
      run: |
        echo "Ngrok running. Keep this window open."
        sleep 21600
